apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-healer-app
  namespace: code-healer
  labels:
    app: code-healer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-healer
  template:
    metadata:
      labels:
        app: code-healer
    spec:
      containers:
        - name: code-healer
          image: parthsinha90/code-healer-react-app:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          securityContext:
            capabilities:
              add: ["NET_BIND_SERVICE"]
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        fsGroup: 101